// src/content/destinations/dive-sites/providencia.content.ts
// import { toAssetUrl } from '../../../constants/assets.schema';
import type { DiveSiteContent } from './types';

export const providenciaDiveSitesContent: Record<string, DiveSiteContent> = {
  'turtle-rock-prov': {
    id: 'turtle-rock-prov',
    nameKey: 'turtleRockProvName',
    destinationId: 'providencia',
    isTopSite: false,
    coordinates: [-81.40537439009262, 13.389974950957608],
    maxDepthMeter: 42,
    maxDepthFt: 140,
    levelRequiredId: 'advanced-open-water-diver',
    difficultyId: 'medium',
    typeIds: ['wall'],
    conditionsIds: ['deep'],
    descriptionKey: 'turtleRockProvDesc',
    tagsIds: ['advanced-only'],
    photos: [], // /images/destinations/providencia/dive-sites/
  },

  'mantas-city-prov': {
    id: 'mantas-city-prov',
    nameKey: 'mantasCityProvName',
    destinationId: 'providencia',
    isTopSite: false,
    coordinates: [-81.37853634485339, 13.312914213771165],
    maxDepthMeter: 9,
    maxDepthFt: 30,
    levelRequiredId: 'any',
    difficultyId: 'easy',
    typeIds: ['reef'],
    conditionsIds: ['boat-entry'],
    descriptionKey: 'mantasCityProvDesc',
    tagsIds: ['manta-rays'],
    photos: [],
  },

  'planchon-prov': {
    id: 'planchon-prov',
    nameKey: 'planchonProvName',
    destinationId: 'providencia',
    isTopSite: false,
    coordinates: [-81.40814570998155, 13.357195213219228],
    maxDepthMeter: 15,
    maxDepthFt: 50,

    levelRequiredId: 'open-water-diver',
    difficultyId: 'easy',
    typeIds: ['wreck'],
    conditionsIds: ['boat-entry'],
    descriptionKey: 'planchonProvDesc',
    tagsIds: ['barracuda'],
    photos: [],
  },

  'felipes-place-prov': {
    id: 'felipes-place-prov',
    nameKey: 'felipesPlaceProvName',
    destinationId: 'providencia',
    isTopSite: false,
    coordinates: [-81.40304064702852, 13.365000317013099],
    maxDepthMeter: 24,
    maxDepthFt: 80,

    levelRequiredId: 'open-water-diver',
    difficultyId: 'easy',
    typeIds: ['reef'],
    conditionsIds: ['boat-entry'],
    descriptionKey: 'felipesPlaceProvDesc',
    tagsIds: ['barracuda'],
    photos: [],
  },

  'nicks-place-prov': {
    id: 'nicks-place-prov',
    nameKey: 'nicksPlaceProvName',
    destinationId: 'providencia',
    isTopSite: false,
    coordinates: [-81.40493681326822, 13.380893565456148],
    maxDepthMeter: 40,
    maxDepthFt: 130,

    levelRequiredId: 'advanced-open-water-diver',
    difficultyId: 'easy',
    typeIds: ['reef'],
    conditionsIds: ['boat-entry'],
    descriptionKey: 'nicksPlaceProvDesc',
    tagsIds: ['biodiversity-hotspot'],
    photos: [],
  },

  'tetes-place-prov': {
    id: 'tetes-place-prov',
    nameKey: 'tetesPlaceProvName',
    destinationId: 'providencia',
    isTopSite: false,
    coordinates: [-81.40697883844926, 13.333210678763905],
    maxDepthMeter: 7,
    maxDepthFt: 23,

    levelRequiredId: 'any',
    difficultyId: 'easy',
    typeIds: ['reef'],
    conditionsIds: ['boat-entry'],
    descriptionKey: 'tetesPlaceProvDesc',
    tagsIds: ['beginner-friendly'],
    photos: [],
  },

  // 'balsat-place-prov': {
  //   id: 'balsat-place-prov',
  //   nameKey: 'balsatPlaceProvName',
  //   destinationId: 'providencia',
  //   isTopSite: false,
  //   coordinates: [-81.3556364910354, 13.391819565527683],
  //   maxDepthMeter: 18,
  //   maxDepthFt: 60,

  //   levelRequiredId: '',
  //   difficultyId: '',
  //   typeIds: [''],
  //   conditionsIds: [''],
  //   descriptionKey: 'balsatPlaceProvDesc',
  //   tagsIds: [''],
  //   photos: [],
  // },

  // 'cayo-cangrejo-prov': {
  //   id: 'cayo-cangrejo-prov',
  //   nameKey: 'cayoCangrejoProvName',
  //   destinationId: 'providencia',
  //   isTopSite: false,
  //   coordinates: [-81.33871685381965, 13.372095646714499],
  //   maxDepthMeter: 18,
  //   maxDepthFt: 60,

  //   levelRequiredId: '',
  //   difficultyId: '',
  //   typeIds: [''],
  //   conditionsIds: [''],
  //   descriptionKey: 'cayoCangrejoProvDesc',
  //   tagsIds: [''],
  //   photos: [],
  // },

  // 'bahia-aguamansa-prov': {
  //   id: 'bahia-aguamansa-prov',
  //   nameKey: 'bahiaAguamansaProvName',
  //   destinationId: 'providencia',
  //   isTopSite: false,
  //   coordinates: [-81.36147084869636, 13.328810890357957],
  //   maxDepthMeter: 18,
  //   maxDepthFt: 60,

  //   levelRequiredId: '',
  //   difficultyId: '',
  //   typeIds: [''],
  //   conditionsIds: [''],
  //   descriptionKey: 'bahiaAguamansaProvDesc',
  //   tagsIds: [''],
  //   photos: [],
  // },

  'bajo-de-los-pargos-prov': {
    id: 'bajo-de-los-pargos-prov',
    nameKey: 'bajoDeLosPargosProvName',
    destinationId: 'providencia',
    isTopSite: false,
    coordinates: [-81.36890965471346, 13.308088230382339],
    maxDepthMeter: 20,
    maxDepthFt: 65,

    levelRequiredId: 'any',
    difficultyId: 'easy',
    typeIds: ['reef'],
    conditionsIds: ['boat-entry'],
    descriptionKey: 'bajoDeLosPargosProvDesc',
    tagsIds: ['beginner-friendly'],
    photos: [],
  },

  // 'el-frances-prov': {
  //   id: 'el-frances-prov',
  //   nameKey: 'elFrancesProvName',
  //   destinationId: 'providencia',
  //   isTopSite: false,
  //   coordinates: [-81.38845475287685, 13.31504329351391],
  //   maxDepthMeter: 18,
  //   maxDepthFt: 60,

  //   levelRequiredId: '',
  //   difficultyId: '',
  //   typeIds: [''],
  //   conditionsIds: [''],
  //   descriptionKey: 'elFrancesProvDesc',
  //   tagsIds: [''],
  //   photos: [],
  // },

  // 'snaper-sure-prov': {
  //   id: 'snaper-sure-prov',
  //   nameKey: 'snaperSureProvName',
  //   destinationId: 'providencia',
  //   isTopSite: false,
  //   coordinates: [-81.40187377549624, 13.3184497821549],
  //   maxDepthMeter: 18,
  //   maxDepthFt: 60,

  //   levelRequiredId: '',
  //   difficultyId: '',
  //   typeIds: [''],
  //   conditionsIds: [''],
  //   descriptionKey: 'snaperSureProvDesc',
  //   tagsIds: [''],
  //   photos: [],
  // },

  'la-cueva-prov': {
    id: 'la-cueva-prov',
    nameKey: 'laCuevaProvName',
    destinationId: 'providencia',
    isTopSite: false,
    coordinates: [-81.40683297950798, 13.372805168198951],
    maxDepthMeter: 40,
    maxDepthFt: 140,

    levelRequiredId: 'advanced-open-water-diver',
    difficultyId: 'medium',
    typeIds: ['reef'],
    conditionsIds: ['boat-entry'],
    descriptionKey: 'laCuevaProvDesc',
    tagsIds: ['deep-dive'],
    photos: [],
  },

  // 'cabeza-de-morgan-prov': {
  //   id: 'cabeza-de-morgan-prov',
  //   nameKey: 'cabezaDeMorganProvName',
  //   destinationId: 'providencia',
  //   isTopSite: false,
  //   coordinates: [-81.39166364959017, 13.377062253235422],
  //   maxDepthMeter: 18,
  //   maxDepthFt: 60,

  //   levelRequiredId: '',
  //   difficultyId: '',
  //   typeIds: [''],
  //   conditionsIds: [''],
  //   descriptionKey: 'cabezaDeMorganProvDesc',
  //   tagsIds: [''],
  //   photos: [],
  // },

  // 'galeon-prov': {
  //   id: 'galeon-prov',
  //   nameKey: 'galeonProvName',
  //   destinationId: 'providencia',
  //   isTopSite: false,
  //   coordinates: [-81.39180950853147, 13.391677672600949],
  //   maxDepthMeter: 18,
  //   maxDepthFt: 60,

  //   levelRequiredId: '',
  //   difficultyId: '',
  //   typeIds: [''],
  //   conditionsIds: [''],
  //   descriptionKey: 'galeonProvDesc',
  //   tagsIds: [''],
  //   photos: [],
  // },

  // 'el-canal-prov': {
  //   id: 'el-canal-prov',
  //   nameKey: 'elCanalProvName',
  //   destinationId: 'providencia',
  //   isTopSite: false,
  //   coordinates: [-81.39341395688811, 13.401468088214628],
  //   maxDepthMeter: 18,
  //   maxDepthFt: 60,

  //   levelRequiredId: '',
  //   difficultyId: '',
  //   typeIds: [''],
  //   conditionsIds: [''],
  //   descriptionKey: 'elCanalProvDesc',
  //   tagsIds: [''],
  //   photos: [],
  // },
} as const;
