// src/content/destinations/dive-sites/santa-marta.content.ts
// import { toAssetUrl } from '../../../constants/assets.schema';
import type { DiveSiteContent } from './types';

export const santaMartaDiveSitesContent: Record<string, DiveSiteContent> = {
  'bajo-del-pescador': {
    id: 'bajo-del-pescador',
    nameKey: 'bajoDelPescadorName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.19631, 11.31663],
    maxDepthMeter: 18,
    maxDepthFt: 60,
    levelRequiredId: 'open-water-diver',
    difficultyId: 'easy',
    typeIds: ['reef'],
    conditionsIds: ['boat-entry'],
    descriptionKey: 'bajoDelPescadorDesc',
    tagsIds: ['reef-fish'],
    photos: [], // /images/destinations/santa-marta/dive-sites/
  },

  'barcaza-profunda-sm': {
    id: 'barcaza-profunda-sm',
    nameKey: 'barcazaProfundaSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.22322, 11.25151],
    maxDepthMeter: 40,
    maxDepthFt: 130,
    levelRequiredId: 'advanced-open-water-diver',
    difficultyId: 'hard',
    typeIds: ['wreck'],
    conditionsIds: ['boat-entry', 'deep', 'good-visibility'],
    descriptionKey: 'barcazaProfundaSmDesc',
    tagsIds: [
      'historical',
      'technical-dive',
      'reef-fish',
      'warm-water',
      'advanced-only',
    ],
    photos: [],
  },

  'barco-hundido-sm': {
    id: 'barco-hundido-sm',
    nameKey: 'barcoHundidoSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.238819, 11.21381],
    maxDepthMeter: 30,
    maxDepthFt: 100,
    levelRequiredId: 'advanced-open-water-diver',
    difficultyId: 'medium',
    typeIds: ['wreck'],
    conditionsIds: ['boat-entry', 'variable-visibility', 'moderate-current'],
    descriptionKey: 'barcoHundidoSmDesc',
    tagsIds: [
      'reef-fish',
      'historical',
      'advanced-only',
      'warm-water',
      'biodiversity-hotspot',
    ],
    photos: [],
  },

  'caga-pajaro-sm': {
    id: 'caga-pajaro-sm',
    nameKey: 'cagaPajaroSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.20035, 11.32104],
    maxDepthMeter: 40,
    maxDepthFt: 130,
    levelRequiredId: 'advanced-open-water-diver',
    difficultyId: 'medium',
    typeIds: ['reef'],
    conditionsIds: [
      'boat-entry',
      'variable-visibility',
      'moderate-current',
      'deep',
    ],
    descriptionKey: 'cagaPajaroSmDescr',
    tagsIds: [
      'reef-fish',
      'turtles',
      'sharks',
      'barracuda',
      'advanced-only',
      'warm-water',
      'biodiversity-hotspot',
      'deep-dive',
      'historical',
    ],
    photos: [],
  },

  'calderon-sm': {
    id: 'calderon-sm',
    nameKey: 'calderonSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.235234, 11.212113],
    maxDepthMeter: 18,
    maxDepthFt: 60,
    levelRequiredId: 'none',
    difficultyId: 'easy',
    typeIds: ['reef'],
    conditionsIds: ['boat-entry', 'shore-entry', 'good-visibility'],
    descriptionKey: 'calderonSmDesc',
    tagsIds: [
      'reef-fish',
      'nudibranchs',
      'macro-life',
      'beginner-friendly',
      'warm-water',
      'photography',
    ],
    photos: [],
  },

  'calichan-sm': {
    id: 'calichan-sm',
    nameKey: 'calichanSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.20035, 11.32104],
    maxDepthMeter: 40,
    maxDepthFt: 130,
    levelRequiredId: 'none',
    difficultyId: 'easy',
    typeIds: ['reef'],
    conditionsIds: [
      'shore-entry',
      'boat-entry',
      'variable-visibility',
      'mild-current',
      'calm-surface',
      'deep',
    ],
    descriptionKey: 'calichanSmDesc',
    tagsIds: [
      'reef-fish',
      'macro-life',
      'beginner-friendly',
      'advanced-only',
      'deep-dive',
      'warm-water',
      'biodiversity-hotspot',
      'photography',
    ],
    photos: [],
  },

  'cantil-granate-sm': {
    id: 'cantil-granate-sm',
    nameKey: 'cantilGranateSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.19468, 11.30207],
    maxDepthMeter: 30,
    maxDepthFt: 100,
    levelRequiredId: 'open-water-diver',
    difficultyId: 'medium',
    typeIds: ['wall'],
    conditionsIds: ['boat-entry', 'variable-visibility', 'moderate-current'],
    descriptionKey: 'cantilGranateSmDesc',
    tagsIds: [
      'reef-fish',
      'macro-life',
      'night-dive',
      'warm-water',
      'biodiversity-hotspot',
      'photography',
    ],
    photos: [],
  },

  'el-coro-sm': {
    id: 'el-coro-sm',
    nameKey: 'elCoroSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.19128, 11.3159],
    maxDepthMeter: 40,
    maxDepthFt: 130,
    levelRequiredId: 'advanced-open-water-diver',
    difficultyId: 'hard',
    typeIds: ['pinnacle'],
    conditionsIds: ['boat-entry', 'moderate-current', 'strong-current', 'deep'],
    descriptionKey: 'elCoroSmDesc',
    tagsIds: [
      'reef-fish',
      'sharks',
      'macro-life',
      'advanced-only',
      'deep-dive',
      'warm-water',
      'biodiversity-hotspot',
      'pelagics',
    ],
    photos: [],
  },

  'el-morro-chico-sm': {
    id: 'el-morro-chico-sm',
    nameKey: 'elMorroChicoSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.22273, 11.25143],
    maxDepthMeter: 30,
    maxDepthFt: 100,
    levelRequiredId: 'open-water-diver',
    difficultyId: 'medium',
    typeIds: ['drift'],
    conditionsIds: [
      'boat-entry',
      'variable-visibility',
      'moderate-current',
      'surge',
    ],
    descriptionKey: 'elMorroChicoSmDesc',
    tagsIds: [
      'reef-fish',
      'drift-dive',
      'warm-water',
      'biodiversity-hotspot',
      'photography',
    ],
    photos: [],
  },

  'el-remanso-sm': {
    id: 'el-remanso-sm',
    nameKey: 'elRemansoSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.20528, 11.27109],
    maxDepthMeter: 12,
    maxDepthFt: 400,
    levelRequiredId: 'none',
    difficultyId: 'easy',
    typeIds: ['reef'],
    conditionsIds: [
      'boat-entry',
      'calm-surface',
      'mild-current',
      'good-visibility',
    ],
    descriptionKey: 'elRemansoSmDesc',
    tagsIds: [
      'reef-fish',
      'macro-life',
      'beginner-friendly',
      'warm-water',
      'night-dive',
      'photography',
    ],
    photos: [],
  },

  'el-torin-sm': {
    id: 'el-torin-sm',
    nameKey: 'elTorinSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.19078, 11.31103],
    maxDepthMeter: 20,
    maxDepthFt: 650,
    levelRequiredId: 'open-water-diver',
    difficultyId: 'medium',
    typeIds: ['reef'],
    conditionsIds: ['boat-entry', 'good-visibility', 'calm-surface'],
    descriptionKey: 'elTorinSmDesc',
    tagsIds: [
      'reef-fish',
      'biodiversity-hotspot',
      'warm-water',
      'photography',
      'beginner-friendly',
    ],
    photos: [],
  },

  'inca-inca-sm': {
    id: 'inca-inca-sm',
    nameKey: 'incaIncaSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.23471, 11.21601],
    maxDepthMeter: 12,
    maxDepthFt: 40,
    levelRequiredId: 'none',
    difficultyId: 'easy',
    typeIds: ['reef'],
    conditionsIds: ['shore-entry', 'calm-surface', 'good-visibility'],
    descriptionKey: 'incaIncaSmDesc',
    tagsIds: [
      'reef-fish',
      'macro-life',
      'beginner-friendly',
      'warm-water',
      'photography',
    ],
    photos: [],
  },

  'la-antena-sm': {
    id: 'la-antena-sm',
    nameKey: 'laAntenaSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.2, 11.261171],
    maxDepthMeter: 18,
    maxDepthFt: 60,
    levelRequiredId: 'open-water-diver',
    difficultyId: 'medium',
    typeIds: ['reef'],
    conditionsIds: ['boat-entry', 'variable-visibility', 'mild-current'],
    descriptionKey: 'laAntenaSmDesc',
    tagsIds: [
      'reef-fish',
      'macro-life',
      'nudibranchs',
      'photography',
      'beginner-friendly',
      'warm-water',
    ],
    photos: [],
  },

  'la-pecera-sm': {
    id: 'la-pecera-sm',
    nameKey: 'laPeceraSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.1917, 11.29571],
    maxDepthMeter: 18,
    maxDepthFt: 60,
    levelRequiredId: 'open-water-diver',
    difficultyId: 'easy',
    typeIds: ['reef'],
    conditionsIds: [
      'boat-entry',
      'calm-surface',
      'good-visibility',
      'mild-current',
    ],
    descriptionKey: 'laPeceraSmDesc',
    tagsIds: [
      'reef-fish',
      'turtles',
      'beginner-friendly',
      'warm-water',
      'biodiversity-hotspot',
      'photography',
    ],
    photos: [],
  },

  'la-piedra-del-chivo-sm': {
    id: 'la-piedra-del-chivo-sm',
    nameKey: 'laPiedraDelChivoSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.19479, 11.32248],
    maxDepthMeter: 15,
    maxDepthFt: 50,
    levelRequiredId: 'open-water-diver',
    difficultyId: 'easy',
    typeIds: ['reef'],
    conditionsIds: [
      'boat-entry',
      'calm-surface',
      'good-visibility',
      'mild-current',
    ],
    descriptionKey: 'laPiedraDelChivoSmDesc',
    tagsIds: [
      'reef-fish',
      'macro-life',
      'beginner-friendly',
      'warm-water',
      'photography',
    ],
    photos: [],
  },

  'la-piedra-del-medio-sm': {
    id: 'la-piedra-del-medio-sm',
    nameKey: 'laPiedraDelMedioSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.19446, 11.29695],
    maxDepthMeter: 25,
    maxDepthFt: 80,
    levelRequiredId: 'open-water-diver',
    difficultyId: 'medium',
    typeIds: ['reef'],
    conditionsIds: ['boat-entry', 'variable-visibility', 'moderate-current'],
    descriptionKey: 'laPiedraDelMedioSmDesc',
    tagsIds: [
      'reef-fish',
      'schooling-fish',
      'barracuda',
      'pelagics',
      'beginner-friendly',
      'warm-water',
      'biodiversity-hotspot',
      'photography',
    ],
    photos: [],
  },

  'la-travesia-sm': {
    id: 'la-travesia-sm',
    nameKey: 'laTravesiaSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.19256, 11.30703],
    maxDepthMeter: 25,
    maxDepthFt: 80,
    levelRequiredId: 'advanced-open-water-diver',
    difficultyId: 'medium',
    typeIds: ['wall'],
    conditionsIds: ['boat-entry', 'variable-visibility', 'moderate-current'],
    descriptionKey: 'laTravesiaSmDesc',
    tagsIds: [
      'reef-fish',
      'schooling-fish',
      'barracuda',
      'pelagics',
      'drift-dive',
      'warm-water',
      'biodiversity-hotspot',
      'photography',
    ],
    photos: [],
  },

  'la-vuelta-negra-sm': {
    id: 'la-vuelta-negra-sm',
    nameKey: 'laVueltaNegraSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.1905, 11.31878],
    maxDepthMeter: 25,
    maxDepthFt: 80,
    levelRequiredId: 'open-water-diver',
    difficultyId: 'medium',
    typeIds: ['wall'],
    conditionsIds: ['boat-entry', 'variable-visibility', 'moderate-current'],
    descriptionKey: 'laVueltaNegraSmDesc',
    tagsIds: [
      'reef-fish',
      'schooling-fish',
      'warm-water',
      'biodiversity-hotspot',
      'photography',
    ],
    photos: [],
  },

  'langostas-sm': {
    id: 'langostas-sm',
    nameKey: 'langostasSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.19552, 11.285358],
    maxDepthMeter: 20,
    maxDepthFt: 65,
    levelRequiredId: 'open-water-diver',
    difficultyId: 'medium',
    typeIds: ['reef'],
    conditionsIds: ['boat-entry', 'variable-visibility', 'mild-current'],
    descriptionKey: 'langostasSmDesc',
    tagsIds: [
      'reef-fish',
      'macro-life',
      'warm-water',
      'biodiversity-hotspot',
      'photography',
    ],
    photos: [],
  },

  'las-barcazas-sm': {
    id: 'las-barcazas-sm',
    nameKey: 'lasBarcazasSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.221257, 11.251176],
    maxDepthMeter: 35,
    maxDepthFt: 115,
    levelRequiredId: 'open-water-diver',
    difficultyId: 'medium',
    typeIds: ['wreck'],
    conditionsIds: ['boat-entry', 'variable-visibility', 'mild-current'],
    descriptionKey: 'lasBarcazasSmDesc',
    tagsIds: [
      'reef-fish',
      'historical',
      'advanced-only',
      'warm-water',
      'biodiversity-hotspot',
      'photography',
    ],
    photos: [],
  },

  'los-carros-sm': {
    id: 'los-carros-sm',
    nameKey: 'losCarrosSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.19123, 11.2917],
    maxDepthMeter: 40,
    maxDepthFt: 130,
    levelRequiredId: 'any',
    difficultyId: 'easy',
    typeIds: ['reef'],
    conditionsIds: ['visibility'],
    descriptionKey: 'losCarrosSmDesc',
    tagsIds: ['schooling-fish'],
    photos: [],
  },

  'sisiguaca-sm': {
    id: 'sisiguaca-sm',
    nameKey: 'sisiguacaSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.203385, 11.270821],
    maxDepthMeter: 20,
    maxDepthFt: 65,
    levelRequiredId: 'open-water-diver',
    difficultyId: 'medium',
    typeIds: ['reef'],
    conditionsIds: ['boat-entry', 'variable-visibility', 'moderate-current'],
    descriptionKey: 'sisiguacaSmDesc',
    tagsIds: [
      'reef-fish',
      'schooling-fish',
      'barracuda',
      'warm-water',
      'biodiversity-hotspot',
      'photography',
    ],
    photos: [],
  },

  'morrito-largo-sm': {
    id: 'morrito-largo-sm',
    nameKey: 'morritoLargoSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.20299, 11.31734],
    maxDepthMeter: 75,
    maxDepthFt: 245,
    levelRequiredId: 'advanced-open-water-diver',
    difficultyId: 'hard',
    typeIds: ['pinnacle'],
    conditionsIds: [
      'boat-entry',
      'variable-visibility',
      'strong-current',
      'deep',
    ],
    descriptionKey: 'morritoLargoSmDesc',
    tagsIds: [
      'reef-fish',
      'advanced-only',
      'technical-dive',
      'deep-dive',
      'drift-dive',
      'warm-water',
      'biodiversity-hotspot',
      'photography',
      'pelagics',
    ],
    photos: [],
  },

  'morro-gaira-sm': {
    id: 'morro-gaira-sm',
    nameKey: 'morroGairaSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.23959, 11.20806],
    maxDepthMeter: 25,
    maxDepthFt: 80,
    levelRequiredId: 'open-water-diver',
    difficultyId: 'medium',
    typeIds: ['reef'],
    conditionsIds: [
      'boat-entry',
      'variable-visibility',
      'mild-current',
      'moderate-current',
    ],
    descriptionKey: 'morroGairaSmDesc',
    tagsIds: [
      'reef-fish',
      'schooling-fish',
      'beginner-friendly',
      'warm-water',
      'biodiversity-hotspot',
      'photography',
    ],
    photos: [],
  },

  'morro-santa-marta-sm': {
    id: 'morro-santa-marta-sm',
    nameKey: 'morroSantaMartaSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.23193, 11.24918],
    maxDepthMeter: 30,
    maxDepthFt: 100,
    levelRequiredId: 'open-water-diver',
    difficultyId: 'easy',
    typeIds: ['reef'],
    conditionsIds: [
      'boat-entry',
      'variable-visibility',
      'strong-current',
      'surge',
    ],
    descriptionKey: 'morroSantaMartaSmDesc',
    tagsIds: [
      'reef-fish',
      'schooling-fish',
      'barracuda',
      'pelagics',
      'advanced-only',
      'warm-water',
      'biodiversity-hotspot',
      'photography',
      'historical',
    ],
    photos: [],
  },

  'oceano-sm': {
    id: 'oceano-sm',
    nameKey: 'oceanoSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.19279, 11.29691],
    maxDepthMeter: 30,
    maxDepthFt: 100,
    levelRequiredId: 'open-water-diver',
    difficultyId: 'easy',
    typeIds: ['drift'],
    conditionsIds: [
      'boat-entry',
      'variable-visibility',
      'strong-current',
      'deep',
    ],
    descriptionKey: 'oceanoSmDesc',
    tagsIds: [
      'reef-fish',
      'schooling-fish',
      'pelagics',
      'barracuda',
      'drift-dive',
      'advanced-only',
      'deep-dive',
      'warm-water',
      'biodiversity-hotspot',
      'photography',
    ],
    photos: [],
  },

  'paneles-sm': {
    id: 'paneles-sm',
    nameKey: 'panelesSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.20007, 11.32509],
    maxDepthMeter: 30,
    maxDepthFt: 100,
    levelRequiredId: 'advanced-open-water-diver',
    difficultyId: 'expert',
    typeIds: ['pinnacle'],
    conditionsIds: ['boat-entry', 'strong-current', 'good-visibility', 'deep'],
    descriptionKey: 'panelesSmDesc',
    tagsIds: [
      'reef-fish',
      'schooling-fish',
      'pelagics',
      'barracuda',
      'turtles',
      'advanced-only',
      'technical-dive',
      'deep-dive',
      'drift-dive',
      'warm-water',
      'biodiversity-hotspot',
      'photography',
    ],
    photos: [],
  },

  'paraiso-sm': {
    id: 'paraiso-sm',
    nameKey: 'paraisoSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.1956, 11.28902],
    maxDepthMeter: 15,
    maxDepthFt: 50,
    levelRequiredId: 'open-water-diver',
    difficultyId: 'easy',
    typeIds: ['reef'],
    conditionsIds: [
      'boat-entry',
      'calm-surface',
      'good-visibility',
      'mild-current',
    ],
    descriptionKey: 'paraisoSmDesc',
    tagsIds: [
      'reef-fish',
      'macro-life',
      'beginner-friendly',
      'warm-water',
      'biodiversity-hotspot',
      'photography',
    ],
    photos: [],
  },

  'paso-del-angel-sm': {
    id: 'paso-del-angel-sm',
    nameKey: 'pasoDelAngelSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.20135, 11.31801],
    maxDepthMeter: 40,
    maxDepthFt: 130,
    levelRequiredId: 'advanced-open-water-diver',
    difficultyId: 'medium',
    typeIds: ['drift'],
    conditionsIds: [
      'boat-entry',
      'variable-visibility',
      'moderate-current',
      'strong-current',
      'deep',
    ],
    descriptionKey: 'pasoDelAngelSmDesc',
    tagsIds: [
      'reef-fish',
      'seahorses',
      'schooling-fish',
      'pelagics',
      'drift-dive',
      'advanced-only',
      'deep-dive',
      'warm-water',
      'biodiversity-hotspot',
      'photography',
    ],
    photos: [],
  },

  'playaca-sm': {
    id: 'playaca-sm',
    nameKey: 'playacaSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.197457, 11.26182],
    maxDepthMeter: 18,
    maxDepthFt: 60,
    levelRequiredId: 'open-water-diver',
    difficultyId: 'easy',
    typeIds: ['reef'],
    conditionsIds: [
      'boat-entry',
      'shore-entry',
      'calm-surface',
      'good-visibility',
      'mild-current',
    ],
    descriptionKey: 'playacaSmDesc',
    tagsIds: [
      'reef-fish',
      'macro-life',
      'beginner-friendly',
      'warm-water',
      'biodiversity-hotspot',
      'photography',
    ],
    photos: [],
  },

  'punta-aguja-sm': {
    id: 'punta-aguja-sm',
    nameKey: 'puntaAgujaSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.19941, 11.31844],
    maxDepthMeter: 30,
    maxDepthFt: 100,
    levelRequiredId: 'open-water-diver',
    difficultyId: 'medium',
    typeIds: ['pinnacle'],
    conditionsIds: [
      'boat-entry',
      'variable-visibility',
      'moderate-current',
      'calm-surface',
    ],
    descriptionKey: 'puntaAgujaSmDesc',
    tagsIds: [
      'reef-fish',
      'schooling-fish',
      'barracuda',
      'pelagics',
      'turtles',
      'beginner-friendly',
      'advanced-only',
      'warm-water',
      'biodiversity-hotspot',
      'photography',
    ],
    photos: [],
  },

  'punta-cabeza-de-negros-sm': {
    id: 'punta-cabeza-de-negros-sm',
    nameKey: 'puntaCabezaNegrosSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.2369, 11.20972],
    maxDepthMeter: 25,
    maxDepthFt: 80,
    levelRequiredId: 'open-water-diver',
    difficultyId: 'medium',
    typeIds: ['reef'],
    conditionsIds: ['boat-entry', 'variable-visibility', 'moderate-current'],
    descriptionKey: 'puntaCabezaNegrosSmDesc',
    tagsIds: [
      'reef-fish',
      'schooling-fish',
      'warm-water',
      'biodiversity-hotspot',
      'photography',
    ],
    photos: [],
  },

  'punta-gaira-sm': {
    id: 'punta-gaira-sm',
    nameKey: 'puntaGairaSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.24067, 11.21908],
    maxDepthMeter: 15,
    maxDepthFt: 50,
    levelRequiredId: 'open-water-diver',
    difficultyId: 'easy',
    typeIds: ['reef'],
    conditionsIds: [
      'boat-entry',
      'calm-surface',
      'good-visibility',
      'mild-current',
    ],
    descriptionKey: 'puntaGairaSmDesc',
    tagsIds: [
      'reef-fish',
      'macro-life',
      'beginner-friendly',
      'warm-water',
      'photography',
    ],
    photos: [],
  },

  'punta-granate-sm': {
    id: 'punta-granate-sm',
    nameKey: 'puntaGranateSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.19361, 11.29087],
    maxDepthMeter: 20,
    maxDepthFt: 65,
    levelRequiredId: 'open-water-diver',
    difficultyId: 'medium',
    typeIds: ['reef'],
    conditionsIds: [
      'boat-entry',
      'good-visibility',
      'variable-visibility',
      'mild-current',
    ],
    descriptionKey: 'puntaGranateSmDesc',
    tagsIds: [
      'reef-fish',
      'nudibranchs',
      'schooling-fish',
      'pelagics',
      'beginner-friendly',
      'warm-water',
      'biodiversity-hotspot',
      'photography',
    ],
    photos: [],
  },

  'punta-venado-sm': {
    id: 'punta-venado-sm',
    nameKey: 'puntaVenadoSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.206387, 11.272809],
    maxDepthMeter: 18,
    maxDepthFt: 60,
    levelRequiredId: 'open-water-diver',
    difficultyId: 'medium',
    typeIds: ['reef'],
    conditionsIds: [
      'boat-entry',
      'calm-surface',
      'good-visibility',
      'mild-current',
    ],
    descriptionKey: 'puntaVenadoSmDesc',
    tagsIds: [
      'reef-fish',
      'octopus',
      'macro-life',
      'night-dive',
      'beginner-friendly',
      'warm-water',
      'biodiversity-hotspot',
      'photography',
    ],
    photos: [],
  },

  'salichan-sm': {
    id: 'salichan-sm',
    nameKey: 'salichanSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.19327, 11.31067],
    maxDepthMeter: 35,
    maxDepthFt: 115,
    levelRequiredId: 'advanced-open-water-diver',
    difficultyId: 'medium',
    typeIds: ['reef'],
    conditionsIds: [
      'boat-entry',
      'variable-visibility',
      'moderate-current',
      'deep',
    ],
    descriptionKey: 'salichanSmDesc',
    tagsIds: [
      'reef-fish',
      'schooling-fish',
      'barracuda',
      'pelagics',
      'advanced-only',
      'deep-dive',
      'warm-water',
      'biodiversity-hotspot',
      'photography',
    ],
    photos: [],
  },

  'salidero-sm': {
    id: 'salidero-sm',
    nameKey: 'salideroSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.19248, 11.30899],
    maxDepthMeter: 14,
    maxDepthFt: 45,
    levelRequiredId: 'advanced-open-water-diver',
    difficultyId: 'hard',
    typeIds: ['drift'],
    conditionsIds: ['boat-entry', 'variable-visibility', 'strong-current'],
    descriptionKey: 'salideroSmDesc',
    tagsIds: [
      'reef-fish',
      'schooling-fish',
      'barracuda',
      'pelagics',
      'drift-dive',
      'advanced-only',
      'warm-water',
      'biodiversity-hotspot',
      'photography',
    ],
    photos: [],
  },

  'el-natalia-sm': {
    id: 'el-natalia-sm',
    nameKey: 'elNataliaSmName',
    destinationId: 'santa-marta',
    isTopSite: false,
    coordinates: [-74.238627, 11.205035],
    maxDepthMeter: 32,
    maxDepthFt: 105,
    levelRequiredId: 'advanced-open-water-diver',
    difficultyId: 'medium',
    typeIds: ['wreck'],
    conditionsIds: ['boat-entry', 'good-visibility', 'mild-current', 'deep'],
    descriptionKey: 'elNataliaSmDesc',
    tagsIds: [
      'reef-fish',
      'schooling-fish',
      'macro-life',
      'historical',
      'advanced-only',
      'warm-water',
      'biodiversity-hotspot',
      'photography',
    ],
    photos: [],
  },
} as const;
